# Generated by Django 2.1.4 on 2018-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
