# Generated by Django 2.1.4 on 2018-12-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moods',
            old_name='title',
            new_name='moodScore',
        ),
    ]
