# Generated by Django 2.1.4 on 2018-12-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0004_auto_20181208_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='moods',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
