# Generated by Django 2.1.4 on 2018-12-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0006_auto_20181208_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaks',
            name='percentile',
            field=models.FloatField(default=0.0),
        ),
    ]
