# Generated by Django 2.1.4 on 2018-12-09 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0008_auto_20181209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaks',
            name='currStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='streaks',
            name='maxEnd',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='streaks',
            name='maxStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
